#!/usr/bin/env bash
# Generated by Obsidian Steward — interactive CLI (TTY) helper. Safe to re-run.
# steward-installer-meta: plugin-version=2.7.2 template=7 prebuilt-pkg=0.13.1 node=20 node-modules=115
#
# Windows (native PowerShell): use install-node-pty-runtime.ps1 in the same folder.
#
# Downloads node-pty-prebuilt-multiarch **node-v115** (Node 20.x ABI).
# Uses independent Node.js (not Obsidian's embedded Node).
#
# Defaults match Obsidian's host OS (not WSL uname). Override OS_ARCH if needed:
#   OS_ARCH=linux-x64 bash install-node-pty-runtime.sh
#
# Usage: install-node-pty-runtime.sh [DEST_DIR]

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
NODE_PTY_PREBUILT_VERSION="${NODE_PTY_PREBUILT_VERSION:-0.13.1}"
NODE_MODULES="${NODE_MODULES:-115}"
DEFAULT_OS_ARCH="${DEFAULT_OS_ARCH:-win32-x64}"

DEST_DIR="${1:-"$SCRIPT_DIR/node-pty-prebuilt"}"
mkdir -p "$DEST_DIR"

resolve_os_arch() {
  case "$(uname -s 2>/dev/null)" in
    Darwin*)
      case "$(uname -m 2>/dev/null)" in
        arm64) echo "darwin-arm64" ;;
        *) echo "darwin-x64" ;;
      esac
      ;;
    Linux*)
      local musl=0
      if ldd --version 2>&1 | grep -qi musl; then musl=1; fi
      local prefix="linux"
      [[ "$musl" -eq 1 ]] && prefix="linuxmusl"
      case "$(uname -m 2>/dev/null)" in
        aarch64|arm64) echo "${prefix}-arm64" ;;
        armv7l|armv6l|arm*) echo "${prefix}-arm" ;;
        i686|i386) echo "${prefix}-ia32" ;;
        *) echo "${prefix}-x64" ;;
      esac
      ;;
    MINGW*|MSYS*|CYGWIN*)
      case "$(uname -m 2>/dev/null)" in
        i686|i386) echo "win32-ia32" ;;
        *) echo "win32-x64" ;;
      esac
      ;;
    *)
      echo "$DEFAULT_OS_ARCH"
      ;;
  esac
}

if [[ "${STW_USE_RUNTIME_PLATFORM:-}" == "1" ]]; then
  OS_ARCH="$(resolve_os_arch)"
else
  OS_ARCH="${OS_ARCH:-$DEFAULT_OS_ARCH}"
fi

TAG="v${NODE_PTY_PREBUILT_VERSION}"
TMP="${DEST_DIR}/.stw-node-pty-download.tar.gz"
ASSET="node-pty-prebuilt-multiarch-v${NODE_PTY_PREBUILT_VERSION}-node-v${NODE_MODULES}-${OS_ARCH}.tar.gz"
URL="https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/${TAG}/${ASSET}"

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required to download the prebuilt binary." >&2
  exit 1
fi

echo "Downloading $ASSET ..."
curl -fsSL "$URL" -o "$TMP"
tar -xzf "$TMP" -C "$DEST_DIR"
rm -f "$TMP"
echo "Extracted into $DEST_DIR"
printf '%s\n' ""
printf '%s\n' "Node-pty prebuilt installed successfully! ✅"
printf '%s\n' ""
printf '%s\n' "Now you can start any interactive programs and your favorite agents like VIM, Gemini, and Claude, etc."
printf '%s\n' ""
printf '%s\n' "Adjust the shell executable, working directory, and add extra interactive programs in the settings."
