# Generated by Obsidian Steward — interactive CLI (TTY) helper. Safe to re-run.
# steward-installer-meta: plugin-version=2.7.2 template=7 prebuilt-pkg=0.13.1 node=20 node-modules=115
#
# Downloads node-pty-prebuilt-multiarch **node-v115** (Node 20.x ABI).
# Uses independent Node.js (not Obsidian's embedded Node).
#
# Defaults match Obsidian's host when this file was generated. Override OS_ARCH if needed:
#   \$env:OS_ARCH = 'linux-x64'; .\install-node-pty-runtime.ps1
#
# macOS / Linux / Git Bash on Windows: prefer install-node-pty-runtime.sh.
#
# Run:
#   powershell -NoProfile -ExecutionPolicy Bypass -File .\install-node-pty-runtime.ps1
#
param(
  [Parameter(Position = 0)]
  [string] $DestDir = ""
)

$ErrorActionPreference = 'Stop'

$ScriptDir = $PSScriptRoot
if ([string]::IsNullOrWhiteSpace($DestDir)) {
  $DestDir = Join-Path $ScriptDir 'node-pty-prebuilt'
}

$NODE_PTY_PREBUILT_VERSION = if ($null -ne $env:NODE_PTY_PREBUILT_VERSION -and $env:NODE_PTY_PREBUILT_VERSION -ne '') {
  $env:NODE_PTY_PREBUILT_VERSION
} else {
  '0.13.1'
}

$NODE_MODULES = if ($null -ne $env:NODE_MODULES -and $env:NODE_MODULES -ne '') {
  $env:NODE_MODULES
} else {
  '115'
}

$DEFAULT_OS_ARCH = if ($null -ne $env:DEFAULT_OS_ARCH -and $env:DEFAULT_OS_ARCH -ne '') {
  $env:DEFAULT_OS_ARCH
} else {
  'win32-x64'
}

function Resolve-StwWinArch {
  if ($env:PROCESSOR_ARCHITECTURE -eq 'x86') {
    return 'win32-ia32'
  }
  return 'win32-x64'
}

if ($env:STW_USE_RUNTIME_PLATFORM -eq '1') {
  $OS_ARCH = Resolve-StwWinArch
} elseif ($null -ne $env:OS_ARCH -and $env:OS_ARCH -ne '') {
  $OS_ARCH = $env:OS_ARCH
} else {
  $OS_ARCH = $DEFAULT_OS_ARCH
}

$ver = $NODE_PTY_PREBUILT_VERSION.Trim()
$ASSET = "node-pty-prebuilt-multiarch-v$ver-node-v$NODE_MODULES-$OS_ARCH.tar.gz"
$URL = "https://github.com/homebridge/node-pty-prebuilt-multiarch/releases/download/v$ver/$ASSET"
$TMP = Join-Path $DestDir '.stw-node-pty-download.tar.gz'

New-Item -ItemType Directory -Force -Path $DestDir | Out-Null

Write-Host "Downloading $ASSET ..."
try {
  Invoke-WebRequest -Uri $URL -OutFile $TMP -UseBasicParsing
} catch {
  Write-Error "Download failed."
  exit 1
}

$tar = Get-Command tar -ErrorAction SilentlyContinue
if (-not $tar) {
  Write-Error 'tar is required to extract the prebuilt binary (included in Windows 10 1903+).'
  exit 1
}

& tar -xzf $TMP -C $DestDir
if ($LASTEXITCODE -ne 0) {
  exit $LASTEXITCODE
}

Remove-Item -Force $TMP -ErrorAction SilentlyContinue
Write-Host "Extracted into $DestDir"
Write-Host ''
Write-Host 'Node-pty prebuilt installed successfully! ✅'
Write-Host ''
Write-Host 'Now you can start any interactive programs and your favorite agents like VIM, Gemini, and Claude, etc.'
Write-Host ''
Write-Host 'Adjust the shell executable, working directory, and add extra interactive programs in the settings.'